### PR TITLE
Added new translation strings

### PR DESCRIPTION
**Pull request by Razortide**

### CODE REVIEW

**Comment by SalieriC** [comment]
Thanks again for your efforts @Razortide. Please note that I made a copy-paste mistake in the last line of the current file.
Currently it reads:
` "SWIM.notification-selectOrTargetOneOrMoreTokens": "Please select one or more tokens."`
this will be changed to
` "SWIM.notification-selectOrTargetOneOrMoreTokens": "Please select or target one or more tokens."`
You may want to change your PR accordingly. =)

**Comment by SalieriC** [comment]
I also just added two more translation strings.

**Comment by Razortide** [comment]
Hey @SalieriC,
I entered the changes accordingly and found a few other things to iron out.

I also found that some (...) SFX do have a colon at the end, while others don't. Shall I enter the colons everywhere?

**Comment by SalieriC** [comment]
I'm inclined to add the colons everywhere because of consistency...

**Comment by Razortide** [comment]
And done :-)

**Pull request merged**
