### PR TITLE
cards support to chase setup

### PR DESCRIPTION
**Pull request by mafamac**
Support cards to Chase setup.

Since foundry v9 has a new cards object and the official module (swade by pinnacle) is using this option instead of tables, I added support to cards in chase setup

### CODE REVIEW

**Comment by SalieriC** [comment]
I haven't seen the need to change this as it offers little benefit but I'll gladly merge a PR concerned with it. But it needs to work. Right now it doesn't let me choose a deck to draw from and reset should shuffle the selected deck. If you want me to merge it please work that out.

Thank you for your efforts anyway. =)

**Comment by mafamac** [comment]
Hello, thank you for the feedback.

I added code to shuffle the deck after resetting it.

I did a check and should list all decks. This is a video showing how it's working for me https://www.youtube.com/watch?v=heLgooDjMfA, please let me know if not working for you I will try to identify the error and fix it.

after a click on cards radio, it should allow you to choose from all decks and deck piles available.

I did it because the official swade module provides a deck with the cards, there is no more table with the cards :/. probably in the near future, people will start using the cards module to host all decks/cards.

I was planning a chase scene for the wiseguy scenario and I realize that I can't use the cards to draw in the scene, only tables.

thank you again, hope these changes work :)

**Comment by SalieriC** [comment]
Yeah, this is now looking much better. I still have some concerns though. First of all I think there should be some defaults here as I want to enable players to just click once. The settings should really only be a concern when they need to make the changes. Thus I'd suggest to set the deck radio button to be the default as well as the card stack (if any) that matches the string of `game.settings.get('swim', 'chaseDeck');`, which is already defined here: https://github.com/mafamac/SWADE-Immersive-Macros/blob/dd5c2b96046bec7ee1223208564a2c90397c5989/swim/scripts/swim_modules/chase_setup.js#L31-L32

The second concern is the size of the dialogue. I'd only show the options relevant to the selection of the radio button instead of making irrelevant ones greyed out. I could do this after merging if you don't want to touch it but feel free to give it a try if you like. You can see an example of how I do it starting here: https://github.com/SalieriC/SWADE-Immersive-Macros/blob/0d0c1eb3b734abcaab7ca74c1d4b82dbcb818874/swim/scripts/swim_modules/effect_builder.js#L767

There is a cards table shipped with SWIM you could've used btw. ^^

**Comment by mafamac** [comment]
Thank you a milion :)

Let me try make those changes :) .. 

I agree the default option should be available to avoid extra click/select.. i'll change it to have the default as configure previously.

I tried to hide the content based on the radio selection using css visiblity and display, no success. let me retry using the example you shared.

**Comment by mafamac** [comment]
I added some visual improvements as your recommendation, also added support for localization.

**Comment by SalieriC** [comment]
Thank you very much. =)

**Pull request merged**
