### PR TITLE
add power effect modifiers

### PR DESCRIPTION
**Pull request by bloy**
Add to effect builder helpers for the following power modifiers:
- Glow
- Shroud
- Hurry
- Hinder
- Lingering Damage

### CODE REVIEW

**Comment by SalieriC** [comment]
Very interesting. I haven't thought of adding power modifiers yet but they make sense. Also you inspired me, now I'm eager to create something for glow/shroud on the tokens light level.
The problem is that this requires users to execute the macro twice in many cases. Maybe it would be better to put them in another selector and push their effect into the changes of the original power AE (instead of making their own AE)? Then the icons wouldn't be needed however. On the topic of icons: If we end up needing them, I'd adjust them in a way that they are consistent with the other icons. I hope you won't mind.
Please give me your thoughts. =)

**Comment by bloy** [comment]
I thought about trying to define a lighting effect, but like with anything swade there were enough corner cases where it didn't seem like the best idea, such as when a token that has an existing light get glow or shroud, it would have to replace the existing light, and the game and canvas effects (such as providing vision to other players) may be affected.

I like the idea of keeping the separate AEs, because then a GM that wants to attach a visual effect to these can do so with something like Automated Animations or Token Variant Art. My approach to this would be to have the effect builder do one thing (make effects) very well, and leave any frills or customization to other modules that do stuff like visual effects very well. 

I suppose adding the modifiers as checkboxes/radio buttons to each and every power is also a possibility as well, but at some point the UI for that gets unwieldy. I don't know if 5 checkboxes for each power, in addition to everything else, gets unwieldy or not. I think I'm still in favor of separate AEs though.

**Comment by SalieriC** [comment]
Okay so coming back to this: I do appreciate your work but I'm not liking it too much. That's not to say it has no chance though. The argument about being unwieldy is very valid and currently, the PEB is very close to becoming unwieldy I think. What would you think of adding a category similar to "other" which is already there? Something like "Modifiers & Trappings" at the bottom after or before "other" and chugging all the modifiers and trappings in there with another selector being rendered then. This way we can take what you did already and would only require a little bit of tweaking. It makes it a bit tidier and thus easier to navigate and also wouldn't get in the way too much for people who don't want to use it.
Would that work for you and would you be willing to make the changes? =)

**Comment by javierriveracastro** [comment]
I'm closing this to do some cleaning as it has been stalled from May.

**Pull request closed without merging**
