### PR TITLE
[Macro] Enhance Chase Setup to customize deck placement

### PR DESCRIPTION
**Pull request by pmoore603**
Adds several fields to the Chase Setup dialog to allow the user to customize card size, deck borders, and deck placement.

### CODE REVIEW

**Comment by SalieriC** [comment]
That's indeed pretty advanced, wow. I'm not sure this is even needed because I feel my layout is great but apparently it is, otherwise you wouldn't have done it. So, thank you. =)
But please edit it in such a way, that it works like before by default (18 cards, aligned to the chase layout I ship in this module), I can make module settings to alter the default values later, after #42 is dealt with; when I get to #43. You only need to do the 0.8.9 version. The other one is for earlier versions and about to be deprecated.

**Comment by pmoore603** [comment]
Your layouts are very nice indeed.  I like how you include the tables in the scenes.
I was looking for a way to do an ad hoc scene and place cards in a custom manner.

My latest push has the cards aligning to your chase layouts.

**Comment by pmoore603** [comment]
Having some configurable default settings are the way to go, I think.  You could also add a button/dropdown/checkbox/whatever that forces the chase deck to use your original settings, and not the configurable default settings.  I'd be glad to help with that once the other issues are committed.

**Comment by SalieriC** [comment]
> Having some configurable default settings are the way to go, I think. You could also add a button/dropdown/checkbox/whatever that forces the chase deck to use your original settings, and not the configurable default settings. I'd be glad to help with that once the other issues are committed.

That is awesome, Thank you very much for your effort and offer of participation. =)
When I set up everything for the settings I'll get back to you. 👍

**Comment by SalieriC** [comment]
Don't worry if I close this PR. I'll pull out the code and set it up in the new branch. Then it'll be merged when I'm done setting up 0.15.0. I've made a tiny adjustment other than that it seems to work really well. I much appreciate your contribution. 👍 
If you like, please DM me on Discord (SalieriC#8263); we can discuss the settings thing more easily there. =)

**Comment by pmoore603** [comment]
👍  I sent a discord friend request to you (Nefarrio#1770)

**Pull request closed without merging**
